        !COMPILER-GENERATED INTERFACE MODULE: Wed Dec  4 12:10:58 2013
        MODULE INITIAL_DATA3__genmod
          INTERFACE 
            SUBROUTINE INITIAL_DATA3(MAXII,IAB,ES)
              INTEGER(KIND=4) :: MAXII
              INTEGER(KIND=4) :: IAB(MAXII)
              REAL(KIND=8) :: ES(MAXII)
            END SUBROUTINE INITIAL_DATA3
          END INTERFACE 
        END MODULE INITIAL_DATA3__genmod
