        !COMPILER-GENERATED INTERFACE MODULE: Wed Aug 19 09:49:32 2015
        MODULE INITIAL_DATA3__genmod
          INTERFACE 
            SUBROUTINE INITIAL_DATA3(MAXII,IAB,ES)
              INTEGER(KIND=4) :: MAXII
              INTEGER(KIND=4) :: IAB(MAXII)
              REAL(KIND=8) :: ES(MAXII)
            END SUBROUTINE INITIAL_DATA3
          END INTERFACE 
        END MODULE INITIAL_DATA3__genmod
