        !COMPILER-GENERATED INTERFACE MODULE: Wed Aug 19 09:49:32 2015
        MODULE INITIAL_DATA1__genmod
          INTERFACE 
            SUBROUTINE INITIAL_DATA1(NE,SNT,CNT,FNT,FNTB,FNTC,FNTD)
              INTEGER(KIND=4), INTENT(IN) :: NE
              REAL(KIND=8), INTENT(INOUT) :: SNT(NE)
              REAL(KIND=8), INTENT(INOUT) :: CNT(NE)
              REAL(KIND=8), INTENT(INOUT) :: FNT(NE)
              REAL(KIND=8), INTENT(INOUT) :: FNTB(NE)
              REAL(KIND=8), INTENT(INOUT) :: FNTC(NE)
              REAL(KIND=8), INTENT(INOUT) :: FNTD(NE)
            END SUBROUTINE INITIAL_DATA1
          END INTERFACE 
        END MODULE INITIAL_DATA1__genmod
