#! /bin/csh -f

  set file    = `pwd`
  set file    = $file:t
#  echo $file

  if !( -d SCF_DATA ) then
    mkdir SCF_DATA
  endif
  set filename = $file'_scf_date'
  echo '---------------------------------------------' >> ./SCF_DATA/$filename.txt
  echo '    put scf data' >> ./SCF_DATA/$filename.txt
  date >> ./SCF_DATA/$filename.txt
  echo '---------------------------------------------' >> ./SCF_DATA/$filename.txt
  echo '  '
  echo 'put scf data in' $file '/SCF_DATA/ directroy'
  set refilename = $file'_rescf'
  set refilename = 'wien'
  cp $file.clmsum ./SCF_DATA/wien.clmsum
  cp $file.in0 ./SCF_DATA/wien.in0
  cp $file.in1 ./SCF_DATA/wien.in1
  cp $file.in2 ./SCF_DATA/wien.in2
  cp $file.in1c ./SCF_DATA/wien.in1c
  cp $file.in2c ./SCF_DATA/wien.in2c
  cp $file.inc ./SCF_DATA/wien.inc
  cp $file.inm ./SCF_DATA/wien.inm
  cp $file.inst ./SCF_DATA/wien.inst
  cp $file.kgen ./SCF_DATA/wien.kgen
  cp $file.klist ./SCF_DATA/wien.klist
  cp $file.struct ./SCF_DATA/wien.struct
  cp $file.vsp ./SCF_DATA/wien.vsp
  echo '  '


  if !( -d HR_DATA ) then
    mkdir HR_DATA
  endif
  set filename = $file'_HR_date'
  echo '---------------------------------------------' >> ./HR_DATA/$filename.txt
  echo '    put hr data' >> ./HR_DATA/$filename.txt
  date >> ./HR_DATA/$filename.txt
  echo '---------------------------------------------' >> ./HR_DATA/$filename.txt
  echo '  '
  echo 'put HR input data in' $file '/HR_DATA/ directroy'
  set filename = $file'_HR'
  cp $file.klist ./HR_DATA/wien_HR.klist
  cp $file.struct ./HR_DATA/wien_HR.struct
  cp $file.output0 ./HR_DATA/wien_HR.output0
  cp $file.output1 ./HR_DATA/wien_HR.output1
  cp $file.output2 ./HR_DATA/wien_HR.output2
  cp $file.outputs ./HR_DATA/wien_HR.outputs
  cp $file.outputt ./HR_DATA/wien_HR.outputt
  cp $file.outputkgen ./HR_DATA/wien_HR.outputkgen
  cp $file.dos1 ./HR_DATA/wien_HR.dos1
  cp $HOME/NFE_HR/calchr ./HR_DATA/calchr
  cp $HOME/NFE_HR/wien.ff_scale_factor ./HR_DATA/wien.ff_scale_factor
  cp $HOME/NFE_HR/LMAX ./HR_DATA/LMAX
  echo '  '
#
