#!/bin/csh -f

set file     = `pwd`
set filename = $file:h
set filename = $filename:t
set psformat = "_Cmax2.ps"
set epsformat = "_Cmax2.eps"

gnuplot -persist << EOF

set title "$filename"
set size 0.7,1.0
set xr[*:30.0]
set xl "{/=30 Energy [eV] }"
set yr[0.0:*]
set yl "{/=30 <{|C|}^2_m_a_x>}"

set yzeroaxis lt 1 lw 2 lc rgb "black"

# linetype=lt, linecolor=lc, linewidth=lw, pointtype=pt, pointsize=ps
# with=w, line=l, color setting=lc rgb "", 
set key box center top
plot "$file/results_so/THHR/TH_HR_gnuplot.DATA" using 1:4 w l lt 1 lw 2 lc rgb "black" title "{/=30 <{|C|}^2_m_a_x>}"

#set size 1.0,1.0
#set terminal postscript color enhanced "Arial" 30
#set out "$filename$psformat"
#replot

set size 1.5,2.1
set terminal postscript eps color enhanced "Arial" 30
set out "$filename$epsformat"
replot

set terminal x11

EOF

